# Generated by Django 5.2.5 on 2025-08-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='name',
            field=models.CharField(default='Sem nome', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='title',
            field=models.CharField(default='Sem titulo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='title',
            field=models.CharField(default='sem titulo', max_length=100),
            preserve_default=False,
        ),
    ]
