# Generated by Django 5.2.5 on 2025-09-16 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='category',
            field=models.CharField(choices=[('lazer', 'Lazer'), ('transporte', 'Transporte'), ('casa', 'Casa'), ('educacao', 'Educação'), ('emergencia', 'Emergência'), ('investimento', 'Investimento'), ('outros', 'Outros')], default='outros', max_length=20),
        ),
        migrations.CreateModel(
            name='ObjectiveDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='finance.objective')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
