# Generated by Django 5.2.5 on 2025-08-29 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_debt_user_expense_user_income_user_objective_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_day', models.IntegerField(help_text='Dia do vencimento (1-31)')),
                ('frequency', models.CharField(choices=[('monthly', 'Mensal'), ('weekly', 'Semanal'), ('yearly', 'Anual')], default='monthly', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta Recorrente',
                'verbose_name_plural': 'Contas Recorrentes',
            },
        ),
    ]
