# Generated by Django 5.2.5 on 2025-09-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_objective_category_objectivedeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
