# Generated by Django 5.2.5 on 2025-08-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_recurringbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringbill',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=10),
        ),
    ]
