# Generated by Django 5.2.5 on 2025-08-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_category_objective_debt_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='objective',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
