# Generated by Django 5.2.5 on 2025-08-30 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_recurringbill_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringBillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('overdue', 'Atrasado')], default='pending', max_length=10)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recurring_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.recurringbill')),
            ],
            options={
                'verbose_name': 'Pagamento de Conta Recorrente',
                'verbose_name_plural': 'Pagamentos de Contas Recorrentes',
                'indexes': [models.Index(fields=['year', 'month'], name='finance_rec_year_c8732e_idx'), models.Index(fields=['status'], name='finance_rec_status_1ce61a_idx')],
                'unique_together': {('recurring_bill', 'year', 'month')},
            },
        ),
    ]
