# Generated by Django 5.2.5 on 2025-08-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_recurringbillpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringbill',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, help_text='Data em que a conta foi desativada', null=True),
        ),
    ]
