# Generated by Django 5.2.5 on 2025-09-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollperioditem',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Data do pagamento (manual)', null=True),
        ),
    ]
