# Generated by Django 5.2.5 on 2025-09-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payrollperioditem_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollperioditem',
            name='payment_type',
            field=models.CharField(choices=[('salary', 'Salário'), ('daily', 'Diária'), ('weekly', 'Semanal'), ('bonus', 'Bônus'), ('extra', 'Hora Extra'), ('advance', 'Adiantamento'), ('other', 'Outros')], default='salary', max_length=20),
        ),
    ]
