# Generated by Django 5.2.5 on 2025-09-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_payrollperioditem_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdvancePayment',
        ),
        migrations.DeleteModel(
            name='Payroll',
        ),
    ]
